# Generated by Django 4.2.1 on 2023-06-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_category_name_category_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_name_category',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
